import { asArray, asObject, asString } from "../core/json.js";
import type { LoadedRecord } from "../core/store.js";
import { oneLine, truncate } from "../core/text.js";
import { markers } from "./briefing.js";
import type { ScoredCandidate } from "./score.js";

const MAX_DECISIONS = 8;
const CLOSED = new Set(["done", "abandoned"]);
const RESULT_LABEL: Record<string, string> = { pass: "Passed", fail: "Failed", error: "Errored" };

export interface PrSummaryInput {
  task: LoadedRecord;
  /** Newest first. */
  checkpoints: readonly LoadedRecord[];
  records: readonly ScoredCandidate[];
}

const cite = (id: string) => `\`${id}\``;

function marked(candidate: ScoredCandidate): string {
  const text = markers(candidate.record.data, candidate.staleness).trim();
  return text ? ` ${text}` : "";
}

/**
 * A pull request description built from records: what the task is, what was decided, which
 * checks were recorded, and what is still open. It reports recorded evidence and never re-runs it.
 */
export function buildPrSummary(input: PrSummaryInput): string {
  const task = input.task.data;
  const taskId = asString(task.id) ?? "";
  const status = asString(task.status) ?? "unknown";
  const owner = asString(asObject(task.owner)?.agent);
  const latest = input.checkpoints[0];
  const lines = [
    `## ${oneLine(asString(task.summary) ?? taskId)}`,
    "",
    oneLine(asString(task.intent) ?? ""),
    "",
    `Aletheic task ${cite(taskId)}: ${status}${owner ? `, owner ${owner}` : ""}.`,
  ];
  const section = (title: string, items: string[]) => {
    if (items.length > 0) lines.push("", `### ${title}`, "", ...items);
  };

  const decisions = input.records.filter(
    (c) => c.record.kind === "decision" && c.record.data.status !== "superseded",
  );
  section("Decisions", [
    ...decisions.slice(0, MAX_DECISIONS).map((c) => {
      const d = c.record.data;
      const prefix = d.status === "proposed" ? "Proposed: " : "";
      const why = truncate(oneLine(asString(d.rationale) ?? ""), 240);
      return `- ${prefix}${oneLine(asString(d.chosen) ?? "")}. Why: ${why} ${cite(c.id)}${marked(c)}`;
    }),
    ...(decisions.length > MAX_DECISIONS
      ? [
          `- ${decisions.length - MAX_DECISIONS} more: ${decisions
            .slice(MAX_DECISIONS)
            .map((c) => cite(c.id))
            .join(", ")}`,
        ]
      : []),
  ]);

  // The latest receipt for each command, in command order.
  const latestByCommand = new Map<string, ScoredCandidate>();
  const receipts = input.records
    .filter((c) => c.record.kind === "receipt")
    .sort(
      (a, b) =>
        (asString(b.record.data.ran_at) ?? "").localeCompare(
          asString(a.record.data.ran_at) ?? "",
        ) || a.id.localeCompare(b.id),
    );
  for (const receipt of receipts) {
    const command = asString(receipt.record.data.command) ?? receipt.id;
    if (!latestByCommand.has(command)) latestByCommand.set(command, receipt);
  }
  const checks = [...latestByCommand.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([command, c]) => {
      const r = c.record.data;
      const result = RESULT_LABEL[asString(r.result) ?? ""] ?? "Recorded";
      const head = asString(asObject(r.git)?.head) ?? "unknown commit";
      const since =
        c.codeChanged === true
          ? ", code has changed since"
          : c.codeChanged === false
            ? ", code unchanged since"
            : "";
      return `- ${result}: \`${oneLine(command)}\` (exit ${String(r.exit_code)}) at ${head}${since}. ${cite(c.id)}${marked(c)}`;
    });
  section("Checks recorded", checks.length > 0 ? checks : ["- None recorded."]);

  const seen = new Set<string>();
  const failed: string[] = [];
  for (const checkpoint of input.checkpoints) {
    for (const item of asArray(checkpoint.data.failed_approaches)) {
      const approach = oneLine(asString(asObject(item)?.approach) ?? "");
      if (!approach || seen.has(approach)) continue;
      seen.add(approach);
      const why = oneLine(asString(asObject(item)?.why_failed) ?? "");
      failed.push(`- ${approach}: ${why} ${cite(asString(checkpoint.data.id) ?? "")}`);
    }
  }
  section("Approaches that did not work", failed);

  if (latest) {
    const latestId = asString(latest.data.id) ?? "";
    section(
      "Open questions",
      asArray(latest.data.open_questions)
        .filter((q): q is string => typeof q === "string")
        .map((q) => `- ${oneLine(q)} ${cite(latestId)}`),
    );
  }

  if (!CLOSED.has(status)) {
    const next = latest ? asString(latest.data.next_safe_action) : asString(task.next_action);
    if (next) section("Next", [`- ${oneLine(next)} ${cite(asString(latest?.data.id) ?? taskId)}`]);
  }

  lines.push(
    "",
    "---",
    "<sub>Generated by `alethic render pr-summary` from records in `.alethic/`. Checks were recorded by agents and not re-run here; ⚠ marks claims that are unverified or may be stale.</sub>",
  );
  return `${lines.join("\n")}\n`;
}
